/**
 * Supabase Database Types for Night Eye
 *
 * This file will be auto-generated by `supabase gen types typescript`
 * once the schema is in place. For now, we define the core shape
 * so TypeScript is happy and we have a contract to build against.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          plan: "starter" | "professional" | "enterprise";
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["organizations"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["organizations"]["Insert"]
        >;
      };
      properties: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          slug: string;
          address: string | null;
          room_count: number | null;
          timezone: string;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["properties"]["Row"],
          "id" | "created_at"
        >;
        Update: Partial<Database["public"]["Tables"]["properties"]["Insert"]>;
      };
      incidents: {
        Row: {
          id: string;
          property_id: string;
          reported_by: string;
          incident_type: string;
          severity: "critical" | "high" | "medium" | "low";
          title: string;
          description: string | null;
          room_number: string | null;
          location: string | null;
          status: "open" | "in_progress" | "resolved" | "closed";
          reported_at: string;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["incidents"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["incidents"]["Insert"]>;
      };
      profiles: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          full_name: string | null;
          role: "admin" | "manager" | "staff" | "viewer";
          department: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["profiles"]["Row"],
          "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      plan_type: "starter" | "professional" | "enterprise";
      severity_level: "critical" | "high" | "medium" | "low";
      incident_status: "open" | "in_progress" | "resolved" | "closed";
      user_role: "admin" | "manager" | "staff" | "viewer";
    };
  };
}

// Convenience type aliases
export type Organization =
  Database["public"]["Tables"]["organizations"]["Row"];
export type Property = Database["public"]["Tables"]["properties"]["Row"];
export type Incident = Database["public"]["Tables"]["incidents"]["Row"];
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
