/**
 * Supabase Database Types for G-Vision
 *
 * This file will be auto-generated by `supabase gen types typescript`
 * once the schema is in place. For now, we define the core shape
 * so TypeScript is happy and we have a contract to build against.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          plan: "starter" | "professional" | "enterprise";
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["organizations"]["Row"],
          "id" | "created_at" | "updated_at" | "settings"
        > & { settings?: Json };
        Update: Partial<
          Database["public"]["Tables"]["organizations"]["Insert"]
        >;
      };
      profiles: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          full_name: string | null;
          role: "admin" | "manager" | "staff" | "viewer";
          department: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["profiles"]["Row"],
          "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      properties: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          slug: string;
          property_type: "accommodation" | "restaurant" | "bar" | "facility" | "staff";
          code_prefix: string | null;
          address: string | null;
          timezone: string;
          room_count: number | null;
          has_room_map: boolean;
          settings: Json;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["properties"]["Row"],
          "id" | "created_at" | "settings"
        > & { settings?: Json };
        Update: Partial<Database["public"]["Tables"]["properties"]["Insert"]>;
      };
      rooms: {
        Row: {
          id: string;
          property_id: string;
          room_code: string;
          floor: number | null;
          position: number | null;
          wing: "low" | "high" | null;
          building: string | null;
          room_type: string | null;
          capacity: number | null;
          metadata: Json;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["rooms"]["Row"],
          "id" | "created_at" | "metadata"
        > & { metadata?: Json };
        Update: Partial<Database["public"]["Tables"]["rooms"]["Insert"]>;
      };
      incident_types: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          department: string | null;
          color: string | null;
          icon: string | null;
          sort_order: number;
          is_active: boolean;
        };
        Insert: Omit<Database["public"]["Tables"]["incident_types"]["Row"], "id">;
        Update: Partial<
          Database["public"]["Tables"]["incident_types"]["Insert"]
        >;
      };
      incidents: {
        Row: {
          id: string;
          organization_id: string;
          property_id: string;
          reported_by: string | null;
          incident_date: string;
          incident_time: string | null;
          incident_type: string;
          title: string;
          description: string | null;
          room_code: string | null;
          site: string | null;
          location: string | null;
          severity: "low" | "medium" | "high";
          primary_impact: "safety" | "operations" | "guest";
          status: "open" | "in_progress" | "resolved" | "closed";
          primary_department: string | null;
          is_escalated: boolean;
          escalated_to: string | null;
          controllable_by_rdm: "yes" | "partial" | "no";
          root_cause: string | null;
          source: string;
          import_batch_id: string | null;
          reported_at: string;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["incidents"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["incidents"]["Insert"]>;
      };
      room_tasks: {
        Row: {
          id: string;
          property_id: string;
          room_code: string;
          task_type: string;
          description: string | null;
          assigned_to: string | null;
          status: "pending" | "done" | "cancelled";
          due_date: string | null;
          completed_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["room_tasks"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["room_tasks"]["Insert"]>;
      };
      import_batches: {
        Row: {
          id: string;
          organization_id: string;
          property_id: string | null;
          uploaded_by: string | null;
          file_name: string;
          file_type: string;
          row_count: number | null;
          error_count: number;
          errors: Json;
          status: string;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["import_batches"]["Row"],
          "id" | "created_at" | "error_count" | "errors"
        > & { error_count?: number; errors?: Json };
        Update: Partial<
          Database["public"]["Tables"]["import_batches"]["Insert"]
        >;
      };
      room_layouts: {
        Row: {
          id: string;
          property_id: string;
          name: string;
          layout_type: string;
          config: Json;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["room_layouts"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<Database["public"]["Tables"]["room_layouts"]["Insert"]>;
      };
      classification_rules: {
        Row: {
          id: string;
          organization_id: string;
          rule_type: string;
          target_value: string;
          keywords: string[];
          priority: number;
          is_active: boolean;
        };
        Insert: Omit<
          Database["public"]["Tables"]["classification_rules"]["Row"],
          "id"
        >;
        Update: Partial<
          Database["public"]["Tables"]["classification_rules"]["Insert"]
        >;
      };
      site_mappings: {
        Row: {
          id: string;
          organization_id: string;
          property_id: string;
          match_type: "prefix" | "text";
          pattern: string;
          priority: number;
        };
        Insert: Omit<Database["public"]["Tables"]["site_mappings"]["Row"], "id">;
        Update: Partial<
          Database["public"]["Tables"]["site_mappings"]["Insert"]
        >;
      };
      compensations: {
        Row: {
          id: string;
          organization_id: string;
          property_id: string;
          incident_id: string | null;
          compensation_type: string;
          amount: number;
          currency: string;
          guest_name: string | null;
          room_code: string | null;
          incident_title: string | null;
          incident_type: string | null;
          notes: string | null;
          approved_by: string | null;
          given_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["compensations"]["Row"],
          "id" | "created_at" | "updated_at"
        >;
        Update: Partial<
          Database["public"]["Tables"]["compensations"]["Insert"]
        >;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      plan_type: "starter" | "professional" | "enterprise";
      severity_level: "low" | "medium" | "high";
      incident_status: "open" | "in_progress" | "resolved" | "closed";
      user_role: "admin" | "manager" | "staff" | "viewer";
      task_status: "pending" | "done" | "cancelled";
      controllability: "yes" | "partial" | "no";
      primary_impact: "safety" | "operations" | "guest";
      property_type: "accommodation" | "restaurant" | "bar" | "facility" | "staff";
      wing_side: "low" | "high";
    };
  };
}

// Convenience type aliases
export type Organization = Database["public"]["Tables"]["organizations"]["Row"];
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Property = Database["public"]["Tables"]["properties"]["Row"];
export type Room = Database["public"]["Tables"]["rooms"]["Row"];
export type IncidentType = Database["public"]["Tables"]["incident_types"]["Row"];
export type Incident = Database["public"]["Tables"]["incidents"]["Row"];
export type RoomTask = Database["public"]["Tables"]["room_tasks"]["Row"];
export type ImportBatch = Database["public"]["Tables"]["import_batches"]["Row"];
export type RoomLayout = Database["public"]["Tables"]["room_layouts"]["Row"];
export type ClassificationRule = Database["public"]["Tables"]["classification_rules"]["Row"];
export type SiteMapping = Database["public"]["Tables"]["site_mappings"]["Row"];
export type Compensation = Database["public"]["Tables"]["compensations"]["Row"];
